### ISSUE TITLE
a marker to show your location

### ISSUE THREAD

**Issue by picomiles** [umap-project/umap#745] opened 2020-02-17 05:04 UTC
At moment you can center map on your location but a marker would be useful to show it

**Comment by Binnette** [comment] 2020-02-17 10:24
Hi @picomiles, this is a duplicate of #639, so I close it. Feel free to follow issue #639.

**Closed by Binnette** 2020-02-17 10:24 UTC

**Comment by picomiles** [comment] 2020-02-17 12:30
Ok, thanks. Sorry, I forgot there was issue #639
