### ISSUE TITLE
feature request : when exporting to geojson

### ISSUE THREAD

**Issue by simogeo** [umap-project/umap#622] opened 2018-08-28 16:05 UTC
Wen exporting to geojson, since all layers are mixed up into a unique file (by geometry type it seems), it would be great to add an extra field with source layer name to be able to distinct them.

(thanks again for the great tool)

**Comment by yohanboniface** [comment] 2023-05-02 14:23
Closing as duplicate of #174

**Closed by yohanboniface** 2023-05-02 14:23 UTC
Labels: enhancement, popular
