### ISSUE TITLE
OpenSeaMap integration

### ISSUE THREAD

**Issue by raqueldeziderio** [umap-project/umap#2005] opened 2024-07-19 13:52 UTC
Dear all,
I was testing the inclusion of OpenSeaMap as a base layer (TMS address) and uMap shows it named as "OpenRiverBoat Map".  Could you, please, tell me if it is the same or a kind of bug?

**Comment by yohanboniface** [comment] 2024-07-22 09:11
Can you please share an URL to a map where you have this issue ?

**Comment by raqueldeziderio** [comment] 2024-07-24 05:33
> Can you please share an URL to a map where you have this issue ?

Hi, Yohan

I cloned the map, because it is part of one project... And I configured it as view and edit only by editors. And included you as an editor (same username that you use in GitHub):
https://umap.openstreetmap.fr/pt-br/map/clone-de-mapa-zc_1097165

In fact, I tested two addresses of OpenSeaMap's TMS and couldn't get the background to change, but I saw that “OpenRiverBoatMap” would be the one that most resembles the OpenSeaMap, so,  I chosen it... It was not an automatic substitution as I wrote before, sorry...

But, my problem persists....Is there any way to put OpenSeaMap as a base layer in the uMap?

The addresses I tried were these, that (I think) are the actual addresses:

http://t1.openseamap.org/seamark/$zoom/%x/$y.png

http://t1.openseamap.org/seamark/

Thanks a lot and congratulations for the uMap! Super! ;)

**Comment by yohanboniface** [comment] 2024-07-24 08:35
The correct tile URL seems to be `https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png`, but it seems broken, or blocked for other domain than their. Nothing we can do about this uMap side, so I suggest you contact them directly to make light on this.

Eg. if you check Leaflet.Provider demo page, you'll see that the openseamap option does not add anything on the map: https://leaflet-extras.github.io/leaflet-providers/preview/

I'm closing here because I think the issue is not related to uMap itself.

**Closed by yohanboniface** 2024-07-24 08:35 UTC

**Comment by yohanboniface** [comment] 2024-07-24 08:40
Ah, I think I understood: it only works for zoom greater or equal to 15.

See an example here:

https://umap.openstreetmap.fr/fr/map/openseamap_1097223#11/49.4521/0.1823

**Comment by yohanboniface** [comment] 2024-07-24 08:42
I'm using the custom overlay:

![image](https://github.com/user-attachments/assets/2b9b2130-4046-4a45-a4ae-4c2cec182c49)

with this URL `https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png`

**Comment by raqueldeziderio** [comment] 2024-07-27 01:59
Thank you, Yohan!!!

I tried very much, but you could resolve this!

Nice weekend for you!!!!
