### ISSUE TITLE
Problem importing geojson

### ISSUE THREAD

**Issue by Cristian-wp** [umap-project/umap#2051] opened 2024-08-09 13:59 UTC
**Describe the bug**
Hello, I have load a dxf file in QGIS, then I exported it as geojson.
I can import the file in my umap project, but after a reload I get all the line ruined by simplify. 
I have already disable it, but I always get the same result reported in the following images.

**To Reproduce**
1. Import the following geojson file in umap from PC: 
[stanza.zip](https://github.com/user-attachments/files/16562105/stanza.zip)

2. Save the map
3. Reload the page
**Expected behavior**
After step1:
<img width="466" alt="2024-08-09 13_17_47-GIS - VMware Workstation 17 Player (Non-commercial use only)" src="https://github.com/user-attachments/assets/127dca0c-2acb-4284-a2a4-d6bef7e70775">

After step3:
<img width="500" alt="2024-08-09 13_18_19-GIS - VMware Workstation 17 Player (Non-commercial use only)" src="https://github.com/user-attachments/assets/464e2531-57ea-4067-81fc-0fcbd29242a8">

**Desktop (please complete the following information):**
 - OS: Windows 11 and Ubuntu 22
 - Browser: Chrome 
 - UMAP Version 2.0.2

**Comment by davidbgk** [comment] 2024-08-09 17:39
@Cristian-wp I cannot reproduce your issue, here is what I have once the map is saved with Simplify=0:
<img width="1183" alt="Capture d’écran, le 2024-08-09 à 13 37 24" src="https://github.com/user-attachments/assets/fc4fa56a-cd96-4820-bb26-29382ad3094b">

Check out that setting:
<img width="1239" alt="Capture d’écran, le 2024-08-09 à 13 36 53" src="https://github.com/user-attachments/assets/0fbfc885-2f71-4aad-898a-ef8a9991e226">

**Comment by davidemiccone** [comment] 2024-08-09 17:46
Hello @davidbgk, 
I'm working with Cristian to this problem.
When we save the map it is okay also for me but at the next reload the map has the problem..... Simplify is set to 0.0

**Comment by davidemiccone** [comment] 2024-08-09 17:54
@davidbgk I added screeshoot to the above comment.

I seems that simplify = 0.0 is not honored.

I try to indagate leafleft code and I see an option to set noClip = true but i don't know how to change uMap code to activate this option.....

**Comment by davidbgk** [comment] 2024-08-09 18:45
What is surprising is that even if I choose to simplify by 10, I still have a more “decent” result than what you have:
<img width="1021" alt="Capture d’écran, le 2024-08-09 à 14 43 25" src="https://github.com/user-attachments/assets/97045346-da76-41ed-a0bf-7d93147b284b">

**Comment by davidemiccone** [comment] 2024-08-09 19:58
Yes, really strange.
We both are using the same stanza.geojson file.
We first saw the problem with a docker installation and uMap version 2.0.2, so we installed uMap 2.5.1 with the traditional method (pip install). But there is no difference.
Which version are you using?

Also on the demo umap.openstreetmap.fr there is the same problem, you can see the problem here:
https://umap.openstreetmap.fr/fr/map/anonymous-edit/1102464:1eZPnlI4XcqM_C6m9y8lduln_znK1JSYYcZwyhoeZ2k
![image](https://github.com/user-attachments/assets/abdc8593-53b0-4aa6-8a3a-3adb97207268)


The zoom that we are using is 24.

10.0 is better also for me, but I expect that 0.0 should be equal just like after map import.

**Comment by davidbgk** [comment] 2024-08-09 20:30
That was a long journey but it appears that https://github.com/umap-project/umap/pull/2019/commits/7aa07709b3e6a7728029a2416613e11a95597273 is the commit responsible for the correct simplification (not sure why yet, that's a huge one).

The good news is that it will be part of the next release :)

**Comment by davidemiccone** [comment] 2024-08-10 10:49
Thank you a lot for your assistence.

>>>The good news is that it will be part of the next release :)
This is really a good news. I hope that will be release soon!

**Comment by davidemiccone** [comment] 2024-09-16 08:54
Hello Yohan,
2.6.3 works well!

I had to remove the maps and re-upload and it works.

Thank you very much :-)

**Comment by davidbgk** [comment] 2024-09-16 13:23
🙌

**Closed by davidbgk** 2024-09-16 13:23 UTC
Labels: bug
