### ISSUE TITLE
Make an option to edit objects, but disable moving them

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [umap-project/umap#1206] opened 2023-07-15 15:32 UTC
**Is your feature request related to a problem? Please describe.**
Hello, when I edit, it sometimes happens again and again that I "accidentally" move objects a little bit, although I actually only wanted to click on them to edit the text field.

Furthermore, it also happens to me that when I have idted an object and then click on "Deactivate editing", the editing is deactivated, but I can still move objects, although that shouldn't actually be the case, right? Does anyone else have this problem?

**Describe the solution you'd like**
Would there be a way to edit, but disable the move or at least fix the problem mentioned above? Thanks.

**Comment by yohanboniface** [comment] 2023-07-17 13:11
Can you give more details on how to reproduce the described issue ? I've never hit myself nor never had such feedback until then, and I'm unable to reproduce.

Browser/OS version and a step by step would help. Thanks!

**Comment by jvmatl** [comment] 2023-09-22 17:38
I have not personally seen the 'still editable after I deactivate editing' problem, but I do agree that it's very easy to accidentally move markers when you are trying to just click on them to access the popup so you can view/edit the metadata. And since there's no 'undo' for this operation, you just have to sort of drag the marker back to where you think it was and hope it's close enough, or re-import all your map markers from the original data source.

To me, the interesting part of the original request is the recognition that sometimes you want to edit _geographic_ features on the map (move markers, change areas boundaries, etc.) and sometimes you only want to edit _metadata_ -- and something like a 'lock features' slider near the edit button would be handy for people who only want to edit/examine map metadata.

**Comment by yohanboniface** [comment] 2024-02-20 07:17
Closing in favor of #1366

**Closed by yohanboniface** 2024-02-20 07:17 UTC
Labels: enhancement, need infos
