### ISSUE TITLE
"someone else has edited the data"

### ISSUE THREAD

**Issue by hermann-san** [umap-project/umap#1038] opened 2023-01-06 16:30 UTC
Hi, 
When I edit my map and add a POI with a description, I get this error message after clicking save

`Oops, someone else has edited the data. You can still save, but changes made by others will be deleted.`

I do save the map anyways by pressing the save  button, deactivate editing and reload the page. The object I've added is gone
I use only one browser tab, so **I don't** have the same map opened twice. 

I know this issue since a few years, and it come's up every now and then. But in the last days it won't go away.

Thanks for having a look into it.

**Comment by Spielmops** [comment] 2023-01-08 19:48
Same error in another way:
Yesterday I made my entries. Today I log in an call my map. Some POI from yesterday are missing. I goto versions and restore the latest: all missing POI are there again. I click onto save and then "

> Oops, someone else has edited the data. You can still save, but changes made by others will be deleted.

Spielmops

**Comment by LucBretagne** [comment] 2023-01-10 12:02
Hi hermann-san and Spielmops, I am having the same issue from time to time and did some testing on it. As far as I can see it has something to do with Firefox (in my case on MacOS) and its caching. For me this helps when the error message pops up:
1. Click on Save Anyway to make sure your data is not lost.
2. Close Firefox (btw. you will see if you are opening your map with another web browser like Chrome or Safari everything is ok and all new data is there)
3. Delete the cache of the last hour in Firefox.
4. Open your map, all the data should show up now.
Good luck!

**Comment by Spielmops** [comment] 2023-01-12 17:54
Seems to be working, I will observe it.

Spielmops

**Comment by hermann-san** [comment] 2023-01-25 21:03
same here. I just had  that issue and it has als worked for me (login with a private browser session). 
thanks @LucBretagne 

Still, it appears to be only a good to know workaround and IMO the root cause should be fixed.

**Comment by Spielmops** [comment] 2023-01-26 18:12
I edited three times until today with deleted cache and everything was okay. I will write this solution into the German help.

Spielmops

**Comment by hermann-san** [comment] 2023-01-26 20:14
the procedure I've used yesterday worked only for yesterday.  Today , I've opened uMap, changed something on a POI, cleared cache and everything from the last hour.  However the edit's I've made are gone again.
Also, opening uMap in  private Browser session doesn't has the data I've added yesterday. So basically , the workaround doesn't work for me. 

I wonder what the root cause is. Is it some  Firefox Add-on that is causing this (like Flag Cookies, Add-Block Plus or something else) ?
I will try another browser to see how it goes.

**Comment by LucBretagne** [comment] 2023-01-27 17:11
On my point of view, it is a clear Firefox caching issue, so you might want to switch to Chrome when editing the map, because it does not come up in this browser. In my Firefox, the issue only appears when I have a slow Internet connection, so it might have something to do with timing.

**Comment by hermann-san** [comment] 2023-01-27 22:36
@LucBretagne Chrome is a workaround I could probably use, but my preferred Browser is Firefox and I think this is quite a major bug in uMap that should be fixed by the uMap developer. I would say this is not something that Firefox should or can fix, but what do I know. I'm not a developer.

**Comment by Spielmops** [comment] 2023-01-29 18:51
@hermann-san: You can get you editing back in "layers". edit layer (pencil), versions. 

And: first clear the cache, then edit ...

Spielmops

**Comment by davidbgk** [comment] 2023-05-01 14:05
@hermann-san @Spielmops can you reproduce the issue since a fix has been provided by @yohanboniface ? (Feb 25.)

If that's the case, please reopen!

**Closed by davidbgk** 2023-05-01 14:05 UTC

**Comment by Shohreh** [comment] 2023-07-08 11:08
Currently getting the error while trying to save changes.

FWIW, About says "Powered by Leaflet, glued by uMap project (version [1.3.7]".
