### ISSUE TITLE
Layer order routinely changing

### ISSUE THREAD

**Issue by Mikefrul** [umap-project/umap#1845] opened 2024-05-21 14:22 UTC
Not sure if it's an actual bug, but the order of my layers changes every other day or so.

**Comment by yohanboniface** [comment] 2024-06-11 13:08
Can you share a map URL so we can have a look ?

**Comment by yohanboniface** [comment] 2024-07-22 12:25
Closing as I cannot reproduce. Please reopen with a step by step to reproduce if you hit this again.

**Closed by yohanboniface** 2024-07-22 12:25 UTC
Labels: bug
