### ISSUE TITLE
Zoom to locality (géocoder) weird centering...

### ISSUE THREAD

**Issue by cquest** [umap-project/umap#304] opened 2016-04-07 10:59 UTC
When using the "zoom to locality" left side icon, the map is not always centered on the lat/lon returned by the geocoder.

Exemple: Créteil

The lat/lon returned by the geocoder is 48.7830/2.4518 but the map is centered on 47.4663/2.4518

**Comment by yohanboniface** [comment] 2016-05-22 23:13
Can't reproduce with new search (with Photon), so closing.

**Closed by yohanboniface** 2016-05-22 23:13 UTC
