### ISSUE TITLE
Multiple editors

### ISSUE THREAD

**Issue by meaz** [umap-project/umap#569] opened 2018-03-31 05:53 UTC
Hi,

I shared the edit link of my map to several people. We noticed that if we connect to it and edit it at the same time, only the changes made by one of us are saved, other editors changings are lost. It would be great if we could work on a map simultenously.

**Comment by yohanboniface** [comment] 2018-07-07 07:44
Duplicate of #468

**Closed by yohanboniface** 2018-07-07 07:44 UTC
