### ISSUE TITLE
SEC_ERROR_EXPIRED_CERTIFICATE on all iframes on different websites - different servers.

### ISSUE THREAD

**Issue by Maxime-83** [umap-project/umap#990] opened 2022-04-07 07:34 UTC
Hello,
Same error on many websites using iframes from umap.openstreetmap.co : SEC ERROR EXPIRED CERTIFICATE, Expire after : Wed, 06 Apr 2022 10:33:20 GMT, using Firefox.

And a message "unavailable" with Chrome.

Who could be interested by the information ?
------------------
Watch exemples here : 
https://gmao-3d.fr/contact/
https://art-infogerance.fr/contact/
https://groupe-axiome.fr/contact/
------------------

Thanks for help.

**Comment by danieldegroot2** [comment] 2022-04-07 13:26
This issue is not present on my end, or seems to have resolved itself.
If this issue persists, post a screenshot (Print Screen) of your dev console (F12); key depends on browser.

**Comment by Maxime-83** [comment] 2022-04-07 14:09
<img width="954" alt="Capture d’écran 2022-04-07 à 16 04 07" src="https://user-images.githubusercontent.com/103174329/162217947-f014c823-6353-452e-bf11-e515237d69f3.png">

Maps have been changed on examples given in the last message, using "umap.openstreetmap.fr"

My computer, both firefox and Chrome, don't want to navigate to "umap.openstreetmap.co", because of the Expired date of certificate. I finally reached the url with a security exception asked to firefox, and the website is working.

**Comment by Maxime-83** [comment] 2022-04-07 14:14
Same result if Adblock plugin is turned OFF.
And new screen shot with the arrows toggled :-P 
<img width="993" alt="Capture d’écran 2022-04-07 à 16 12 39" src="https://user-images.githubusercontent.com/103174329/162219643-4283eedb-ac68-4aeb-81ab-20e2911b156f.png">

**Comment by davidbgk** [comment] 2023-05-01 15:14
I'm closing it as I cannot reproduce, I guess the certificate has been updated since then.

**Closed by davidbgk** 2023-05-01 15:14 UTC
