### ISSUE TITLE
Wrong point name displays on hover

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#383] opened 2016-09-30 15:22 UTC
On hover, some points display another's point name instead of their own. 

Issue encountered on Firefox, Chrome, and IE 11, using
- different maps ([1](http://u.osmfr.org/m/19632/), [2](http://u.osmfr.org/m/96589/))
- different computers (Win7, Debian)

Problems occurs after zooming, but not before.

[Video of the issue](https://webcloud.zaclys.com/index.php/s/T2iglEsbWlM20N9/download) ("Le Cut Massena" keeps showing everywhere, while there's only one)

**Comment by brianboru100** [comment] 2016-10-14 19:48
I've got exactly this problem too!

**Comment by mhoebeke** [comment] 2016-11-16 14:43
The same problem occurs on maps with multiple layers, when the user uses the layers widget to hide a layer. On hover, all the markers display the same name.

**Comment by yohanboniface** [comment] 2020-03-21 18:19
Can't reproduce, I guess this has been fixed in a way or another since that time.

**Closed by yohanboniface** 2020-03-21 18:19 UTC
