### ISSUE TITLE
Slow search map by name due to missing index

### ISSUE THREAD

**Issue by cquest** [umap-project/umap#854] opened 2020-11-27 11:18 UTC
On a large umap instance, the search by name of maps gets very slow due to lack of index on tsvector.

Here is a extract of PG log:

2020-11-27 10:49:49.263 UTC [1595955] umap@umap LOG:  duration: 1370.105 ms  statement: SELECT COUNT(*) AS "__count" FROM "umap_map" WHERE ("umap_map"."share_status" = 1 AND (to_tsvector(unaccent(name)) @@ plainto_tsquery(unaccent('Lexi'))))

2020-11-27 10:49:50.997 UTC [1595955] umap@umap LOG:  duration: 1730.913 ms  statement: SELECT "umap_map"."id", "umap_map"."name", "umap_map"."slug", "umap_map"."description", "umap_map"."center"::bytea, "umap_map"."zoom", "umap_map"."locate", "umap_map"."licence_id", "umap_map"."modified_at", "umap_map"."owner_id", "umap_map"."edit_status", "umap_map"."share_status", "umap_map"."settings" FROM "umap_map" WHERE ("umap_map"."share_status" = 1 AND (to_tsvector(unaccent(name)) @@ plainto_tsquery(unaccent('Lexi')))) ORDER BY "umap_map"."modified_at" DESC  LIMIT 4

As unaccent and to_tsvector are not IMMUTABLE, it is not possible to simply add the missing index.
unaccent can be update to immutable, but to_tsvector needs a language code to become immutable.

A switch to pg_trgm may be a better option.

**Comment by yohanboniface** [comment] 2023-05-05 13:25
Did you finally create the index ? :)

**Comment by yohanboniface** [comment] 2023-05-10 08:38
Closing as duplicate of #519

**Closed by yohanboniface** 2023-05-10 08:38 UTC
Labels: need infos
