### ISSUE TITLE
Enhancement: Limit editing capabilities

### ISSUE THREAD

**Issue by miguelvipe** [umap-project/umap#471] opened 2017-03-31 14:29 UTC
Hi,

I'm finding uMap extremely useful so far for our research applications. However there´s an issue that we couldn't find a sloution for: We would like to limit end user editing capabilities. That is, letting map users add a point, but not modify previous users points. Is there a simple way to do this and we are missing it somehow?

Cheers
Miguel

**Comment by sfkeller** [comment] 2020-09-13 00:15
Duplicate of #768  and #52  ?

**Comment by yohanboniface** [comment] 2023-05-03 09:09
CLosing as duplicate of #52 and #584. We'll try to work on this soon.

**Closed** 2023-05-03 09:09 UTC
Labels: enhancement
