### ISSUE TITLE
Wishlist - Ability to superimpose an image on the map

### ISSUE THREAD

**Issue by Codain** [umap-project/umap#386] opened 2016-10-02 20:06 UTC
I've a high resolution map of the inside of a big building and I would like to superimpose it on the map (for instance a PNG with transparency).

As a starting point, the file can be stored on another server and not on the UMAP server.

The picture can then be rotated, translated and resized in UMAP.

Would be a nice feature :+1:

**Comment by Codain** [comment] 2016-10-02 20:08
By the way, superimpose an SVG would be even more awasome!

**Comment by yohanboniface** [comment] 2016-10-02 20:17
Duplicate of #315

**Closed by yohanboniface** 2016-10-02 20:17 UTC
