### ISSUE TITLE
Adding a way to filter data from URL/iframe

### ISSUE THREAD

**Issue by maxchesnel** [umap-project/umap#705] opened 2019-07-23 15:16 UTC
Dear dev's,

I am interested in a way to filter my data on a Umap directly from the URL. This would use a text string as if it was already applied to the text box on top of browsed data.

Please could you add this functionality?

Thanks you

**Comment by Binnette** [comment] 2020-02-16 14:12
Hum. Please confirm my understanding.

You want url like so?
https://umap.openstreetmap.fr/fr/map/my_map?showLayer1=myLayer&showLayer2=otherLayer

Is that so?

**Comment by Binnette** [comment] 2020-02-16 19:26
This issue is similar to #699

**Comment by FBeneville** [comment] 2023-02-09 13:01
Hi, the tiltle seems to be my question but it's not the way you understanding it @Binnette.
I'm looking for a way to filter the features in a layer mening something like this:
https://umap.openstreetmap.fr/fr/map/my_map?showLayer1=myLayer?type=type1

**Comment by yohanboniface** [comment] 2024-11-20 14:45
Duplicate of #2023

**Closed by yohanboniface** 2024-11-20 14:45 UTC
Labels: duplicate, enhancement
