### ISSUE TITLE
Dynamic display according to the presence or absence of a tag in a popup or side panel

### ISSUE THREAD

**Issue by clwacker** [umap-project/umap#1373] opened 2023-10-19 13:23 UTC
I suggest adding the possibility of displaying elements in a popup or side panel depending on whether a tag is present or not, from the dynamic properties of the interaction options.

Something like:
**if** Tag present **then** display text and Tag value **else** something **endif**

For example: 
if start_date exist then 
Year : {start_date}
else
endif

This would allow better control of the display in a popup or side panel, and avoid displaying unnecessary lines.

Thanks.

**Comment by yohanboniface** [comment] 2023-12-05 16:48
Makes sense. Closing as duplicate of #884 but indeed a needed feature.

**Closed by yohanboniface** 2023-12-05 16:48 UTC
Labels: enhancement

**Comment by forteller** [comment] 2023-12-14 17:30
Is this about the ability to show and hide items on the map according to tags, not just layers? I wanted to request that feature, and found this issue when searching, but I'm not sure if it's asking the same thing or if I should create a new issue. Thanks!
