### ISSUE TITLE
docker installation – redis support

### ISSUE THREAD

**Issue by geimist** [umap-project/umap#1618] opened 2024-02-18 13:19 UTC
I have not yet succeeded in getting redis to run in conjunction with the Docker image. 
I'm hoping for improvement because the maps with many layers in Chrome is lagging.

Everything works basically fine without redis.
What am I doing wrong?
Can you please help me?

<hr>
I have done the following things so far:

<details>
  <summary>Here's my docker-compose file:</summary>

The redis configuration comes from [here](https://github.com/umap-project/umap/pull/801)

```
version: '3'
services:
  db:
    image: postgis/postgis:14-3.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /volume3/docker/umap/POSTGRESQL_DATA:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - /volume3/docker/umap/redis:/data
    environment:
      - loglevel=notice

  app:
    image: umap/umap:1.13.1
    ports:
      - "8031:8000"
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - REDIS_URL=redis://redis:6379/0
      - SITE_URL=https://map.example.com/
      - STATIC_ROOT=/srv/umap/static
      - MEDIA_ROOT=/srv/umap/uploads
    volumes:
      - /volume3/docker/umap/conf/umap.conf:/etc/umap/umap.conf
      - /volume3/docker/umap/STATIC_ROOT:/srv/umap/static
      - /volume3/docker/umap/MEDIA_ROOT:/srv/umap/uploads
    depends_on:
      - db
      - redis
```
</details>

I have added the following to the configuration file `umap.conf` based on the information [on this page](https://git.nethuis.nl/pommi/docker-umap/src/branch/master/umap.conf#L103) at the end of the `umap.conf`:
```
import environ
from umap.settings.base import *   # pylint: disable=W0614,W0401
env = environ.Env()
CACHES = {'default': env.cache('REDIS_URL', default='locmem://')}
```

The log from the umap container showed me that the redis module is missing in Python.
I installed it manually as follows:
```
docker exec -it umap-app-1 pip install redis
```

If I now start uMap, I see traffic in redis for the first time, but the website only shows an error message ("Oops, Server error...") and the container also crashed.
In the log I see errors due to a missing SECRET_KEY, which is specified in the `umap.conf`, but is probably overwritten due to the command `from umap.settings.base import *`. 

<details>
  <summary>Here's the container log file after container starts:</summary>

```   
Loaded local config from /etc/umap/umap.conf
Connection alive for > 0s
Connection alive for > 1s
Connection alive for > 2s
Connection alive for > 3s
Connection alive for > 4s
Connection alive for > 5s
Loaded local config from /etc/umap/umap.conf
[36;1mOperations to perform:[0m
"[1m  Apply all migrations: [0madmin
[36;1mRunning migrations:[0m
  No migrations to apply.
Loaded local config from /etc/umap/umap.conf

"0 static files copied to '/srv/umap/static'
Loaded local config from /etc/umap/umap.conf
Compressing... done
Compressed 3 block(s) from 13 template(s) for 1 context(s).
[uWSGI] getting INI configuration from docker/uwsgi.ini
[uwsgi-static] added mapping for /static => /srv/umap/static
[uwsgi-static] added mapping for /uploads => /srv/umap/uploads
*** Starting uWSGI 2.0.21 (64bit) on [Sun Feb 18 12:16:30 2024] ***
compiled with version: 10.2.1 20210110 on 08 January 2024 15:57:28
os: Linux-4.4.302+ #69057 SMP Fri Jan 12 17:02:28 CST 2024
nodename: umap-app-1
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /srv/umap
detected binary path: /venv/bin/uwsgi
"!!! no internal routing support
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1476 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:36138 (port auto-assigned) fd 3
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
"Python version: 3.11.3 (main
PEP 405 virtualenv detected: /venv
Set PythonHome to /venv
Python main interpreter initialized at 0x7f8bb40ed558
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507880 bytes (495 KB) for 4 cores
*** Operational MODE: preforking ***
Loaded local config from /etc/umap/umap.conf
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f8bb40ed558 pid: 7 (default app)
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7)
"spawned uWSGI worker 1 (pid: 35
"spawned uWSGI worker 2 (pid: 36
"spawned uWSGI worker 3 (pid: 37
"spawned uWSGI worker 4 (pid: 38
spawned uWSGI http 1 (pid: 39)
gateway "uWSGI http 1" has been buried (pid: 39)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /srv/umap
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (127.0.0.1:36138)
running /venv/bin/uwsgi
[uWSGI] getting INI configuration from docker/uwsgi.ini
[uwsgi-static] added mapping for /static => /srv/umap/static
[uwsgi-static] added mapping for /uploads => /srv/umap/uploads
*** Starting uWSGI 2.0.21 (64bit) on [Sun Feb 18 12:16:36 2024] ***
compiled with version: 10.2.1 20210110 on 08 January 2024 15:57:28
os: Linux-4.4.302+ #69057 SMP Fri Jan 12 17:02:28 CST 2024
nodename: umap-app-1
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /srv/umap
detected binary path: /venv/bin/uwsgi
"!!! no internal routing support
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1476 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8000 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:40114 (port auto-assigned) fd 4
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
"Python version: 3.11.3 (main
PEP 405 virtualenv detected: /venv
Set PythonHome to /venv
Python main interpreter initialized at 0x7fcdc3644558
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507880 bytes (495 KB) for 4 cores
*** Operational MODE: preforking ***
Loaded local config from /etc/umap/umap.conf
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fcdc3644558 pid: 7 (default app)
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 7)
"spawned uWSGI worker 1 (pid: 42
"spawned uWSGI worker 2 (pid: 43
"spawned uWSGI worker 3 (pid: 44
"spawned uWSGI worker 4 (pid: 45
spawned uWSGI http 1 (pid: 46)   

```   

</details>

<details>
  <summary>Here is the container log file after a request:</summary>

```  
Loaded local config from /etc/umap/umap.conf
Connection alive for > 0s
Connection alive for > 1s
Connection alive for > 2s
Connection alive for > 3s
Connection alive for > 4s
Connection alive for > 5s
Loaded local config from /etc/umap/umap.conf
[36;1mOperations to perform:[0m
"[1m  Apply all migrations: [0madmin
[36;1mRunning migrations:[0m
  No migrations to apply.
Loaded local config from /etc/umap/umap.conf

"0 static files copied to '/srv/umap/static'
Loaded local config from /etc/umap/umap.conf
Compressing... done
Compressed 3 block(s) from 13 template(s) for 1 context(s).
[uWSGI] getting INI configuration from docker/uwsgi.ini
[uwsgi-static] added mapping for /static => /srv/umap/static
[uwsgi-static] added mapping for /uploads => /srv/umap/uploads
*** Starting uWSGI 2.0.21 (64bit) on [Sun Feb 18 12:17:38 2024] ***
compiled with version: 10.2.1 20210110 on 08 January 2024 15:57:28
os: Linux-4.4.302+ #69057 SMP Fri Jan 12 17:02:28 CST 2024
nodename: umap-app-1
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /srv/umap
detected binary path: /venv/bin/uwsgi
"!!! no internal routing support
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1476 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:33135 (port auto-assigned) fd 3
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
"Python version: 3.11.3 (main
PEP 405 virtualenv detected: /venv
Set PythonHome to /venv
Python main interpreter initialized at 0x7ff4876ad558
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507880 bytes (495 KB) for 4 cores
*** Operational MODE: preforking ***
Loaded local config from /etc/umap/umap.conf
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7ff4876ad558 pid: 7 (default app)
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7)
"spawned uWSGI worker 1 (pid: 26
"spawned uWSGI worker 2 (pid: 27
"spawned uWSGI worker 3 (pid: 28
"spawned uWSGI worker 4 (pid: 29
spawned uWSGI http 1 (pid: 30)
Internal Server Error: /de/map/trolley-zittau_3
Traceback (most recent call last):
"  File \"/venv/lib/python3.11/site-packages/django/core/handlers/exception.py\"
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/utils/deprecation.py\"
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/middleware.py\"
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py\"
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py\"
    self.storages = [
                    ^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py\"
"    storage_class(*args
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py\"
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/core/signing.py\"
"    key=_cookie_signer_key(settings.SECRET_KEY)
                           ^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/conf/__init__.py\"
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[pid: 29|app: 0|req: 1/1] 172.21.0.1 () {64 vars in 1724 bytes} [Sun Feb 18 12:18:43 2024] GET /de/map/trolley-zittau_3?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=false&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=null&onLoadPanel=undefined&captionBar=false => generated 5186 bytes in 61 msecs (HTTP/1.1 500) 3 headers in 122 bytes (1 switches on core 0)
Internal Server Error: /de/map/
Traceback (most recent call last):
"  File \"/venv/lib/python3.11/site-packages/django/core/handlers/exception.py\"
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/utils/deprecation.py\"
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/middleware.py\"
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py\"
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py\"
    self.storages = [
                    ^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py\"
"    storage_class(*args
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py\"
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/core/signing.py\"
"    key=_cookie_signer_key(settings.SECRET_KEY)
                           ^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/conf/__init__.py\"
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[pid: 26|app: 0|req: 1/2] 172.21.0.1 () {60 vars in 1175 bytes} [Sun Feb 18 12:18:49 2024] GET /de/map/ => generated 5186 bytes in 56 msecs (HTTP/1.1 500) 3 headers in 122 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
"  File \"/venv/lib/python3.11/site-packages/django/core/handlers/exception.py\"
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/utils/deprecation.py\"
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/middleware.py\"
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py\"
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py\"
    self.storages = [
                    ^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py\"
"    storage_class(*args
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py\"
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/core/signing.py\"
"    key=_cookie_signer_key(settings.SECRET_KEY)
                           ^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/conf/__init__.py\"
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[pid: 27|app: 0|req: 1/3] 172.21.0.1 () {58 vars in 1105 bytes} [Sun Feb 18 12:18:49 2024] GET /favicon.ico => generated 5186 bytes in 72 msecs (HTTP/1.1 500) 4 headers in 145 bytes (1 switches on core 0)
gateway "uWSGI http 1" has been buried (pid: 30)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /srv/umap
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (127.0.0.1:33135)
running /venv/bin/uwsgi
[uWSGI] getting INI configuration from docker/uwsgi.ini
[uwsgi-static] added mapping for /static => /srv/umap/static
[uwsgi-static] added mapping for /uploads => /srv/umap/uploads
*** Starting uWSGI 2.0.21 (64bit) on [Sun Feb 18 12:19:28 2024] ***
compiled with version: 10.2.1 20210110 on 08 January 2024 15:57:28
os: Linux-4.4.302+ #69057 SMP Fri Jan 12 17:02:28 CST 2024
nodename: umap-app-1
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /srv/umap
detected binary path: /venv/bin/uwsgi
"!!! no internal routing support
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1476 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8000 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:33574 (port auto-assigned) fd 4
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
"Python version: 3.11.3 (main
PEP 405 virtualenv detected: /venv
Set PythonHome to /venv
Python main interpreter initialized at 0x7f0472432558
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507880 bytes (495 KB) for 4 cores
*** Operational MODE: preforking ***
Loaded local config from /etc/umap/umap.conf
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f0472432558 pid: 7 (default app)
"uWSGI running as root
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 7)
"spawned uWSGI worker 1 (pid: 33
"spawned uWSGI worker 2 (pid: 34
"spawned uWSGI worker 3 (pid: 35
"spawned uWSGI worker 4 (pid: 36
spawned uWSGI http 1 (pid: 37)
```   
</details>

**Comment by davidbgk** [comment] 2024-02-18 15:46
From what I understand, you are missing the `SECRET_KEY` env var for your image.

I'm keeping this issue open as we should better [document that here](https://docs.umap-project.org/en/master/deploy/docker/).

**Comment by geimist** [comment] 2024-02-18 16:56
Thank you for your reply.
I will wait patiently then.

**Comment by davidbgk** [comment] 2024-02-18 16:58
@geimist the new image has been pushed 👍 (but you'll have to set the `SECRET_KEY` anyway!)

**Comment by geimist** [comment] 2024-02-18 17:22
Unfortunately, this image still does not start. Even if I comment out the section regarding redis in `umap.conf`. Incidentally, this was already the case with version 2.0.0, although I don't have the log to compare.
(It can't be the favicon [last entry], can it?)

<details>
  <summary>Here's the log:</summary>

```
Loaded local config from /etc/umap/umap.conf
Connection alive for > 0s
Connection alive for > 1s
Connection alive for > 2s
Connection alive for > 3s
Connection alive for > 4s
Connection alive for > 5s
Loaded local config from /etc/umap/umap.conf
Traceback (most recent call last):
"  File \"/venv/bin/umap\"
    sys.exit(main())
             ^^^^^^
"  File \"/venv/lib/python3.11/site-packages/umap/bin/__init__.py\"
    management.execute_from_command_line()
"  File \"/venv/lib/python3.11/site-packages/django/core/management/__init__.py\"
    utility.execute()
"  File \"/venv/lib/python3.11/site-packages/django/core/management/__init__.py\"
    self.fetch_command(subcommand).run_from_argv(self.argv)
"  File \"/venv/lib/python3.11/site-packages/django/core/management/base.py\"
"    self.execute(*args
"  File \"/venv/lib/python3.11/site-packages/django/core/management/base.py\"
"    output = self.handle(*args
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/core/management/base.py\"
"    res = handle_func(*args
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py\"
    self.check(databases=[database])
"  File \"/venv/lib/python3.11/site-packages/django/core/management/base.py\"
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/core/checks/registry.py\"
"    new_errors = check(app_configs=app_configs
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/core/checks/urls.py\"
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/core/checks/urls.py\"
    return check_method()
           ^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/urls/resolvers.py\"
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/utils/functional.py\"
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/urls/resolvers.py\"
"    patterns = getattr(self.urlconf_module
                       ^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/utils/functional.py\"
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/urls/resolvers.py\"
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/usr/local/lib/python3.11/importlib/__init__.py\"
"    return _bootstrap._gcd_import(name[level:]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"<frozen importlib._bootstrap>\"
"  File \"<frozen importlib._bootstrap>\"
"  File \"<frozen importlib._bootstrap>\"
"  File \"<frozen importlib._bootstrap>\"
"  File \"<frozen importlib._bootstrap_external>\"
"  File \"<frozen importlib._bootstrap>\"
"  File \"/venv/lib/python3.11/site-packages/umap/urls.py\"
    url=staticfiles_storage.url("umap/favicons/favicon.ico")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py\"
"    return self._url(self.stored_name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py\"
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
"  File \"/venv/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py\"
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'umap/favicons/favicon.ico'
```
</details>

**Comment by yohanboniface** [comment] 2024-02-19 08:36
Which command was this ? `umap collectstatic` or something else ?

**Comment by geimist** [comment] 2024-02-19 09:47
Only startup the container with image v2.0.1.

**Comment by yohanboniface** [comment] 2024-02-19 12:10
Can you check with 2.0.2 ?

**Comment by geimist** [comment] 2024-02-19 14:06
Thank you very much. The current version is now running again. Great work 👍
<hr>
Redis still has no traffic though. Now I don't know whether I should wait for further information regarding the redis implementation (@davidbgk referred to a documentation to be improved), or whether it should actually run with my current configuration and the error is somewhere else.

**Comment by davidbgk** [comment] 2024-02-19 23:09
@geimist I was referring to the lack of documentation around the `SECRET_KEY` env var, I do not have an example with Redis to document.

**Comment by yohanboniface** [comment] 2024-02-20 06:25
>  I'm hoping for improvement because the maps with many layers in Chrome is lagging.

Out of curiosity, what is the bottleneck you've identified, and what do you expect from Redis in this situation ?

**Comment by geimist** [comment] 2024-02-20 13:32
The server load does not really jump up when the map is opened. I cannot recognize an obvious bottleneck. Redis should be an 1st attempt to minimize the problem by caching. 

Chart of the 1st loading of the map:
![Bildschirmfoto 2024-02-20 um 14 27 39](https://github.com/umap-project/umap/assets/29315520/8f73b733-7a54-4811-b107-14a058184ea8)

[I imported the map to umap.openstreetmap.fr](https://umap.openstreetmap.fr/de/map/delivery-areas_1027097). 
Here, too, I can observe the same thing. The problem also only seems to occur with Chrome. You are welcome to give it a try. Especially when clicking on individual areas and when zooming, the map is partially destroyed (tiles are missing, areas are hidden but also control elements are lost).
It may also be a problem in Chrome itself (but I have tried it on several devices).

**Comment by davidbgk** [comment] 2024-02-20 13:36
<img width="928" alt="Capture d’écran, le 2024-02-20 à 08 35 06" src="https://github.com/umap-project/umap/assets/3556/ae33de84-d8bc-4388-a123-f55239080527">

I guess the issue is not uMap in that case 😅 

Having all shapes within the same datalayer might help!

**Comment by geimist** [comment] 2024-02-20 14:25
Thank you for your feedback.
Since I want to release elements individually in an iFrame, I chose the path via individual layers (URL parameter: ...`&datalayers=xyz`...). I had not found any other approach.

**Comment by yohanboniface** [comment] 2024-04-17 08:09
Closing at it seems no action is needed from us, but please reopen if you still need help.

**Closed by yohanboniface** 2024-04-17 08:09 UTC
