### ISSUE TITLE
highligh on over

### ISSUE THREAD

**Issue by robibrazze** [umap-project/umap#838] opened 2020-11-07 09:24 UTC
Hi,
i think that improve umpa whit the function "highlight on over" it is a good thing.
When i click on the layer or search the layer i would like gemetry to be highlighted...

I have installad Umap in local on ubunto and it work fine, if i find i solution for "highlight on over" i write here.

Roberto

**Comment by yohanboniface** [comment] 2020-11-08 08:27
Thanks for the suggestion. :)

Closing as duplicate of #334

**Closed by yohanboniface** 2020-11-08 08:27 UTC
