### ISSUE TITLE
Display measure not showing in Spanish

### ISSUE THREAD

**Issue by Yonoesio** [umap-project/umap#2083] opened 2024-08-30 09:34 UTC
When I use the ruler to measure a distance, it doesn't show the value and only shows the variable "translated" {distancia} km, {área} ha

Using Spanish Translation

![image](https://pics.dhoserver.net/i/82b76386-011a-49f6-91d5-b0980a62d54d.jpg)

**Comment by yohanboniface** [comment] 2024-09-11 18:21
Should be fixed since last release.

The origin of the issue is that the translation had translated the variables inside the string (eg. `{measure}`). I fixed that, but anyone can participate to the translations here: https://www.transifex.com/openstreetmap/umap/dashboard/

**Closed by yohanboniface** 2024-09-11 18:21 UTC
Labels: bug
