### ISSUE TITLE
Editing Umap style

### ISSUE THREAD

**Issue by OuzhoudeOulifu** [umap-project/umap#574] opened 2018-04-09 17:35 UTC
I tried to import a Json map style created in maputnik in a Umap layer but it did not do anything.
Is there any way of using a custom map style with Umap?

**Comment by yohanboniface** [comment] 2023-11-29 21:23
Closing as old. Please reopen if needed!

Maybe duplicate of #606

**Closed by yohanboniface** 2023-11-29 21:23 UTC
Labels: enhancement
