### ISSUE TITLE
Searchbar partially out of screen on mobile

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#376] opened 2016-09-24 09:40 UTC
Search bar goes partially out of screen when search is in full screen.

Not only the menu hides a part of the bar, but the bar itself extends out of screen.

Tested on Samsung Galaxy S4 and FairePhone 2 (both 5" screen).

![umap-mobile](https://cloud.githubusercontent.com/assets/17235663/18807537/32c2e07a-824a-11e6-8dc6-c5429d6b3788.png)

**Comment by yohanboniface** [comment] 2016-09-24 22:02
Controls being over the search bar should be fixed on next release.

But I'm unable to reproduce the bar width issue atm.

**Closed** 2020-03-21 18:21 UTC
