### ISSUE TITLE
Suggestion routing

### ISSUE THREAD

**Issue by klosteinmann** [umap-project/umap#847] opened 2020-11-19 10:44 UTC
Just a suggestion don't know if it meets the scope of the project. Adding route caluclation & route planing to uMap. I found the map very useful for business integration and missing routing in that regard if people wanted to know how to get there from Point A to B they don't have any other useful way but to use another app or map like Google Maps.

**Comment by yohanboniface** [comment] 2023-05-11 10:05
Closing as duplicate of #297

**Closed by yohanboniface** 2023-05-11 10:05 UTC
