### ISSUE TITLE
Layer order broke on update

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#375] opened 2016-09-24 09:11 UTC
Hi, 

Following the 23/9/16 update, layer ordering broke in "About" & "Data browser"

Layers display in random order. Even on cloned maps, layer ordering is now different.

Reordering layers with the new graphical _doesn't_ fix the problem.

Plus, reordering this way doesn't produce coherent results.

I've ordered layers from 01 to 10 on two similar maps (one original, one cloned). On the original, layers are now ordered in this way :
- 4 A
- 2 B
- 3 C
- 1 D 

Where alphabetic order overcomes numeric order. On the clone, no order appears, neither alphabetic nor numeric.

Newly created maps don't seem affected ([example](https://umap.openstreetmap.fr/en/map/ordering-bug_103889)). But most of my already existing maps are. Noticeably, my private maps aren't affected.

**Comment by yohanboniface** [comment] 2016-09-24 21:52
> doesn't

- please do not use bold
- add a link to a map where the issue appears
- describe order you are expecting on this map

**Comment by druxstr** [comment] 2016-09-24 23:08
Sorry about the bold :(

Issue appeared on multiple maps \:

1. http://u.osmfr.org/m/101589/ (issue still visible)
2. http://u.osmfr.org/m/81302/ (issue still visible)
3. http://u.osmfr.org/m/96589/ (issue not visible anymore, used a trick to reorder)
   - I can provide a screenshot showing the issue for this one, but I don't have it right now
4. http://u.osmfr.org/m/99498/ (issue not visible anymore, I had to reorder before tomorrow)

Expected order for these maps \:

- 01. Layer name
- 02. Layer name
- ...
- 10. Layer name

There seems to be 2 problems : 

- 1st, update broke ordering
- 2d, using numbers to reorder didn't work

I managed to restore the original ordering on the 4th map by switching from numbers (*01. Layer name, 02. Layer name...*) to letters (*A. Layer name, B. Layer name*) to order alphabetically, and *then* switch back to numbers for ordering. It's the only thing that worked. Reordering layers without renaming them did not work.

**Comment by yohanboniface** [comment] 2016-09-25 06:54
> I managed to restore the original ordering on the 4th map by switching from numbers (01. Layer name, 02. Layer name...) to letters (A. Layer name, B. Layer name) to order alphabetically, and then switch back to numbers for ordering. It's the only thing that worked. Reordering layers without renaming them did not work. 

Have you tried to reorder manually by drag'n'drop? That's a new feature.
I thought the answer was yes from your first message, but not I'm in doubt.

**Comment by druxstr** [comment] 2016-09-25 07:43
I tried drag'n'drop reordering multiples times. But it only worked partially.

Some layers were reordered, some were not.

**Comment by yohanboniface** [comment] 2016-09-25 20:20
> Some layers were reordered, some were not.

That's not a good news. Sadly, I'm unable to reproduce, even using a clone of your map.
I'll need more info to be able to know what's going on, and try to fix.
It can be either an edge case of the feature, an issue with the browser, etc.
Please try to narrow down by:
- testing on another browser
- testing with another computer
- trying to break down what you are doing when you reproduce the issue to point to some specific element

**Comment by druxstr** [comment] 2016-09-25 22:02
I've tried with different maps, different browsers (FF, Chromium), and broke down every step. Here's what I've got for now \:

I'm able to consistently break layer ordering by cloning a map *that hasn't been modified since the update*. If the map is new or has been modified since (e.g renaming, reordering layers), I do not encounter any problem. Here's some tests maps \:

- original map, untouched since the update http://u.osmfr.org/m/101800/
- clone of 101800, using Chromium http://u.osmfr.org/m/104084/
- clone of 101800, using Chromium again http://u.osmfr.org/m/104089/
- clone of 101800, using Firefox http://u.osmfr.org/m/104090/

For each clones, the layer order has changed. Original was 1, 2,... 10. Clones are 10, 9,... 1. I didn't edit theses clones in anyway. They're just as they were generated.

Concerning reordering : I've produced more clones of 101800 and tried to reorder layers by drag'n'drop using a similar process  \: 

- drag layer 1 before layer 10, 
- layer 2 after layer 1, 
- layer 3 after 2, 
- and so on until layers are ordered from 1 to 10
- save

This works fine with Firefox, not with Chromium. Here are 2 maps made following this process \:
 
- using chromium, reordering failed http://u.osmfr.org/m/104086/
- using chromium, reordering failed but different order http://u.osmfr.org/m/104100/
- using FF, reordering succeeded http://u.osmfr.org/m/104094/

I also tried to change only one layer then save, but here again, I've had difficulties : changes not saved, layer order mixed up again. That's what I got for now.

**Comment by yohanboniface** [comment] 2016-09-30 12:53
Following #379 I've reworked a bit the layer ordering.
Can you have a new try and give feedback?
Thanks in advance!

**Comment by druxstr** [comment] 2016-10-03 20:04
Unfortunately, the issues remains.

- New clones of my test map (101800), are still generated with a different order than the original
- Reordering by drag'n'drop still produces erratic results

Plus, while I didn't edit any of my maps, their layer order has now changed. Maps that were sorted 1, 2, 3... 10 are now sorted 10... 3, 2, 1.

For what it worth, here's my gut feeling \:

- The "reverse order" problem with clones is sort related.
- The "drag'n'drop reordering" is not. It's a saving issue.

When using drag'n'drop reordering, the save button is often unavailable, even after having changed the layer order. The "map has been updated" message often doesn't show, or shows pretty late. It's actually pretty hard to save changes.

If I'm right, that could explain why drag'n'drop reordering always produces different and unpredictable results, while cloning the map produces a reversed, but still coherent order.

**Comment by lopss** [comment] 2016-10-06 23:41
Hi,

I have trouble reordering layers by drag&drop too.
My config : Firefox ESR 45.4.0 Debian Jessie

- I have this problem on this two maps
https://umap.openstreetmap.fr/en/map/reseau-de-bus-sotraco-ouagadougou-burkina-faso_58808
https://umap.openstreetmap.fr/en/map/carteinnov-suivi-de-la-cartographie-des-lieux-dinn_101662

- But it's working on
https://umap.openstreetmap.fr/en/map/projet-ieda-cartographie-des-districts-sanitaires-_59363#9/13.2413/-2.3730

- Description of actions/reactions when it's not working
   - open the map in edition mode
   - drag&drop layers to reorder them
   - hit "Save"
   - right layer panel is leaving the screen smoothly on the right
   - but "Save" and "Cancel" buttons stay active/clickable
   - 2min later, nothing happen. I press F5 to refresh and I've a warning message
   ![capture du 2016-10-06 22 34 26](https://cloud.githubusercontent.com/assets/20402274/19174345/9a61400a-8c1d-11e6-85e7-f9bb103e3978.png)
   - I choose "Stay on page"
   - Some time later I have the message "Vos modifications ont bien été sauvegardées". "Save" and "Cancel" button are not clickable anymore.
   - Refresh by F5, no warning,
   - My reordering is lost and I still have a bad order.

- Note
   - I can save other kind of modifications : edit a layer title, create a new marker, edit a marker name
   - About you @yohanboniface  asking " Can you open the developer console before clicking save then do a screenshot of the full page (including the console) when you feel the map is not updating anymore?", here it is (hope it is what you want) :
   ![selection_004](https://cloud.githubusercontent.com/assets/20402274/19174419/308d88f4-8c1e-11e6-8921-721fb4310b57.png)

Thanks for all :) can give precisions if needed

**Comment by yohanboniface** [comment] 2016-10-07 06:55
> here it is (hope it is what you want) 

Not really. I need the console to be opened when loading the map and until the end of the process.
The screenshot you added shows another scenarios than the one described.

Maybe adding me as editor of one of the map where the issue happen can help.

**Comment by yohanboniface** [comment] 2016-10-07 07:59
OK, I think I've sort of reproduced the issue with a clone of the map (which I couldn't until now with other map facing the issue). I'm in Jordan right now, not sure I can find time to deal with that before next week when I'm back to Paris.

**Comment by yohanboniface** [comment] 2016-10-07 13:47
Release a fix (at least the bug I'm able to reproduce). Can you test again an report feedback? Thanks! :)

**Comment by augustindo** [comment] 2016-10-09 12:48
Hi !

Thanks a lot for reactivity.

I've been able to fixe the layers order by drag&drop here :  https://umap.openstreetmap.fr/en/map/carteinnov-suivi-de-la-cartographie-des-lieux-dinn_101662

But not here : https://umap.openstreetmap.fr/en/map/reseau-de-bus-sotraco-ouagadougou-burkina-faso_58808

For the 1st one I've reordered once and Saved : almost all layers were saved in the good order but I had to reorder again 2 layers and Save again. Now it's OK.

For the 2nd one I've tried to add you as an editor but I can't manage this : I'm going to report now an other issue and came back here to copy/paste the link.

**Comment by druxstr** [comment] 2016-10-09 14:19
Still got the same issues (with FF & Chromium), but it feels better.

* new clones of 101800 are still generated with a "reverse" order
* drag'n'drop reordering still produced unexpected results in
    * http://u.osmfr.org/m/104086/
    * http://u.osmfr.org/m/104100/
    * http://u.osmfr.org/m/104094/
    * http://u.osmfr.org/m/103889/

This said, saving is easier and less buggy. 

Drag'n'drop reordering also seems to work better. There's often only one layer wrongly placed on the first try, and I manage to get the expected order by reordering/saving on the 2d try.

**Comment by LucN31** [comment] 2020-06-14 05:39
Hi,
It remains difficult to order layers using drag&drop function. 
Dragging one layer to move it causes erratic changes for the others layers.

Is it possible to add an option at the map level to choose an alphanumeric layer order ?
It could help in some cases.

Thanks,
Luc.

**Comment by yohanboniface** [comment] 2023-12-05 14:31
This issue seems to be still valid after all those years, but I'm still unable to reproduce.

Here is a test map:

https://umap.openstreetmap.fr/fr/map/test-ordering_994821

Can one of you having the issue in their own maps:
- clone this map (backup/import), in order to be the only one working on it
- try to reproduce the issue with the map has it is
- if the bug is reproduced, describe the step by step
- if not try to add more layers/data, anything that can help reproducing, and again describe the step by step

This can be related to:
- the OS
- the browser / browser version
- some specific data
- some specific way of drag'n'dropping

Thanks in advance for your help!

**Comment by jschleic** [comment] 2023-12-30 20:50
Steps to reproduce (for me):

1. Import and save the Test map https://umap.openstreetmap.fr/fr/map/test-ordering_994821.
2. Reload
3. Drag "Red" to the bottom (after Calque 1)
4. Save (Network analysis shows "Blue" is transferred as POST to the server)
5. Reload -- Unchanged ordering of the layers. Red is still second-last.

**Closed** 2023-12-31 10:16 UTC
