### ISSUE TITLE
uMap Description Box Limits

### ISSUE THREAD

**Issue by kwalshe62** [umap-project/umap#1130] opened 2023-06-07 08:38 UTC
**Describe the bug**
Hi, in the past few days, I noticed a nice new feature which, when I click on a marker, zooms me to the geographical location. However, the description box has become limited where there is a lot of text/photographs. Such information was previously viewable by a scrolling facility which is no longer available. 

**To Reproduce**
1. Go to '...' (VERY IMPORTANT, we need to know which instance of uMap is concerned!)

**Expected behavior**

**Screenshots**
See the bottom and right of the screenshot.
![image](https://github.com/umap-project/umap/assets/135322314/e7393651-beba-4c12-8e0d-7007634672a8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Desktop and iPhone and iPad

**Additional context**

**Comment by yohanboniface** [comment] 2023-06-07 08:55
Hi @kwalshe62 thanks for your report.

It's a duplicate of #1126 and should now be release on umap.openstreetmap.fr, if it's the uMap instance you use.

**Closed by yohanboniface** 2023-06-07 08:55 UTC
Labels: bug
