### ISSUE TITLE
Add https support to Tiny/Permalink urls http://u.osmfr.org/m/xxxxxx/ 

### ISSUE THREAD

**Issue by Wikinaut** [umap-project/umap#977] opened 2022-01-13 10:59 UTC
Currently, the permalinks such as http://u.osmfr.org/m/xxxxxx/ lack https support. I suggest to add the correct support.

**Comment by yohanboniface** [comment] 2023-06-08 05:39
Duplicate of #594

**Closed by yohanboniface** 2023-06-08 05:39 UTC
Labels: enhancement
