### ISSUE TITLE
need help with some problems with account creation 

### ISSUE THREAD

**Issue by poloarqueologicodeviseu** [umap-project/umap#728] opened 2019-11-24 19:37 UTC
Hi

I'm trying to create an uMap account and have encountered two problems:

1- github link doesn't work
using https://umap.openstreetmap.fr/login/github/  returns an error=redirect_uri_mismatch etc

2- Using openstreemap work but...
My username in osm is "Polo Arqueológico de Viseu" (somethin like Polo%20Arqueol%C3%B3gico%20de%20Viseu) so when I try use it to create an account uMap returns PoloArqueolgicodeViseu  This means that  "ó" is missing :(

**Comment by Binnette** [comment] 2020-02-16 13:31
I think this is an encoding issue.

**Comment by Binnette** [comment] 2020-02-16 20:01
Duplicate of #663

**Comment by Binnette** [comment] 2020-02-20 10:01
Link with: #695, #186

**Closed** 2023-06-23 16:32 UTC
Labels: bug, duplicate
