### ISSUE TITLE
Cancel button

### ISSUE THREAD

**Issue by Clairedesf** [umap-project/umap#830] opened 2020-10-14 10:40 UTC
When pressing the Cancel button at the top right of the screen, it canceled many many changes at one time, sending me back to an old version of my work. The first time I used the cancel button hoping to cancel my last action, it brought me back several actions earlier. I kept making additions to my map. And when used the cancel button again, many many changes I made were canceled even if I had saved my work in the meantime. I closed my work and disconnected from my session hoping to recover my last saved version but it did not happen. For the time being, I won't continue using umap and will rather use google mymaps until it is solved. I would really need a cancel button that cancels only the last action.
Thanks

**Comment by yohanboniface** [comment] 2020-10-21 11:18
I understand the annoyance, but it's not that easy to fix, and I'm close to be the unique dev working on uMap, and with little free time to work on this lately.

> The first time I used the cancel button hoping to cancel my last action, it brought me back several actions earlier. 

Yes, that's how it works currently.

> And when used the cancel button again, many many changes I made were canceled even if I had saved my work in the meantime.

That should not be the case, and if it is, it's a bug, and I'm interested by a way to reproduce.

**Comment by yohanboniface** [comment] 2023-06-20 14:05
Duplicate of #1107

**Closed** 2023-06-23 16:33 UTC
Labels: UX, UI
