### ISSUE TITLE
No https for u.osmfr.org ?

### ISSUE THREAD

**Issue by deuzeffe** [umap-project/umap#594] opened 2018-06-23 21:06 UTC
Hello,

u.osmfr.org seems unreachable in https. It's only me or something else ?

Thx for the answer whatever it is.

**Comment by yohanboniface** [comment] 2018-06-26 05:56
cc @cquest @jocelynj

**Comment by deuzeffe** [comment] 2018-06-27 18:38
Pppfff... Dire que j'avais commencé à ouvrir le ticket sur osm-fr/infra ;)

**Comment by jocelynj** [comment] 2018-06-27 20:32
This redirect is handled directly by gandi, and I'm not sure if they have https redirect.
```
$ host u.osmfr.org
u.osmfr.org is an alias for webredir.vip.gandi.net.
```

I was wondering - does the redirect work with a url with a map ?

**Comment by deuzeffe** [comment] 2018-06-28 17:36
Some tests from user(land): 
1. HTTPS Everywhere off
- http://u.osmfr.org -> http://umap.openstreetmap.fr
- http://u.osmfr.org/m/229664/ -> http://umap.openstreetmap.fr/fr/map/faculte-de-pharmacie-limoges_229664#16/45.8140/1.2353
- https://u.osmfr.org/, https://u.osmfr.org/m/229664/ -> host unreachable

2. HTTPS Everywhere on (explicit for openstreetmap.fr)
- http://u.osmfr.org -> https://umap.openstreetmap.fr
- http://u.osmfr.org/m/229664/ -> https://umap.openstreetmap.fr/fr/map/faculte-de-pharmacie-limoges_229664#16/45.8140/1.2353
- (https://u.osmfr.org/, https://u.osmfr.org/m/229664/ -> host unreachable )

HTH

**Comment by jocelynj** [comment] 2018-06-30 17:01
Thanks, it means the redirect by gandi is useful, as it keeps the map URL. The only missing thing is the https support, and I couldn't find any documentation on it on Gandi website.

**Comment by deuzeffe** [comment] 2018-07-06 20:39
Any answer from Gandi's support?

**Comment by jocelynj** [comment] 2018-07-14 18:35
I've contacted Gandi, and they are already aware of the problem of missing https, and are investigating possible solutions.

**Comment by jocelynj** [comment] 2018-07-14 18:38
So, I see three solutions:
  - don't support https on *.osmfr.org.
  - in addition, redirect to https instead of http.
  - move the redirection service to a server handled by OSM-FR.

Do we really need https on this redirection for now ?

**Comment by yohanboniface** [comment] 2018-07-14 18:47
> Do we really need https on this redirection for now ?

I'd say so. A lot of people are using browser extensions to force https.

**Comment by eehpcm** [comment] 2018-09-04 16:11
@jocelynj 
> Do we really need https on this redirection for now ?

This is not as important a reason as people with browser extensions forcing https, so not as urgent.  But it is another reason to do something about it.  Recent versions of most browsers won't allow javascript to interrogate the device's GPS unless the web site is https.  So not having https on u.osmfr.org silently breaks the "Centre map on your location" button.  What happens then is somebody like me raises an issue that the button isn't working.

**Comment by eehpcm** [comment] 2018-09-04 17:40
@jocelynj 

I did some testing with telnet.

>So, I see three solutions:
>    don't support https on *.osmfr.org.

That's not a solution.  That's the problem.  u.osmfr.org is refusing connections on port 443.  It can't redirect because it's not listening.

`[pla@sma` ~]$ telnet u.osmfr.org 80
Trying 217.70.184.50...
Connected to webredir.vip.gandi.net (217.70.184.50).
Escape character is '^]'.
HEAD / HTTP/1.0
Host: u.osmfr.org

HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 04 Sep 2018 17:35:49 GMT
Content-Type: text/html
Connection: close
Location: http://umap.openstreetmap.fr
Cache-Control: max-age=10800

Connection closed by foreign host.`

Versus

`[pla@sma ~]$ telnet u.osmfr.org 443
Trying 217.70.184.50...
telnet: connect to address 217.70.184.50: Connection refused
telnet: Unable to connect to remote host: Connection refused
`

The redirect might still fail even if you get Gandi to support https for u.osmfr.org, but without that the redirect cannot work.

**Comment by yohanboniface** [comment] 2018-09-12 09:43
cf #637

**Comment by eehpcm** [comment] 2018-09-12 12:10
Some alternative solutions for you.

- Using the location button with http pops up a box saying "Requires a secure connection: use https to access the site."  That way you'll no longer get people raising issues that the location button doesn't work.  Instead you'll get people raising issues it doesn't happen automatically. :)

- As above, but a "Requires a secure connection.  Access via https yes/no" dialogue appears and the yes button changes the scheme.

- As above, but settings have an option "If location button pressed on insecure connection, complain/ask/silently negotiate secure connection."

- I've not played with nginx but from what I've read, the rewrite stuff appears to be similar in concept to Apache's.  So change the rewrite rule to have a target of https://umap.openstreetmap.fr instead of http://umap.openstreetmap.fr.  If I understand the nginx docs correctly, this requres nothing more than the addition of the letter "s" in the correct place.  Not perfect, because you still won't be able to use https://u.osmfr.org but using http://u.osmfr.org will take you to https://umap.openstreetmap.fr, which is better than what we have now.

**Comment by yohanboniface** [comment] 2018-09-12 12:13
The problem is not the redirection, is that we are not yet able to force https: when we force https, we also need all requests to be in https, including background layer, remote data, etc. which is not yet the casee.
That's indeed the target though.

**Comment by eehpcm** [comment] 2018-09-12 12:38
@yohanboniface 

Since I don't have detailed knowledge of the inner workings, maybe I'm missing something.  But if I go to https://umap.openstreetmap.fr works, so wouldn't changing window.location to that fix things?  Sure, it would mean a complete page load, but it ought to work.

Similarly, on gandi, it looks like this would work (and is a better solution):

`server {
    listen 80;
    server_name u.osmfr.org;
    return 302 https://umap.openstreetmap.fr$request_uri;
}`

Return 302 rather than 301 so u.osmfr.org/m/12345 can be bookmarked as such.  Use "https" rather than "$scheme" to force TLS no matter how they went to gandi.

So what am I missing?  Are there additional weird things happening behind the scenes if I go via gandi?

**Comment by nlgranger** [comment] 2020-04-20 12:58
Is this issue still being worked on? The website defaults to http and I would like to know which functionalities of the website still don't support https. For examples, is the data from private maps sent unencrypted?

**Comment by yohanboniface** [comment] 2020-04-21 06:13
>  I would like to know which functionalities of the website still don't support https

Custom user data may or may not be in https: custom background, custom icons, remote data…

**Comment by xerz-one** [comment] 2020-09-25 13:58
If you want to always avoid using plain HTTP and use Firefox, you might be interested in enabling `dom.security.https_only_mode` at `about:config`

**Comment by jocelynj** [comment] 2023-06-11 18:28
@cquest : gandi now has support for https redirect, but I don't have permission to add one on osmfr.org domain. Could you add the relevant permission?

**Comment by cquest** [comment] 2023-07-14 07:55
Je n'ai pas accès en modification non plus depuis mon compte gandi :(

Le domaine a été modifié par Gandi depuis qu'il nous est offert ou quelque chose du genre ?

J'ai demandé le renvoi de code d'accès qui va arriver sur contact@

**Comment by yohanboniface** [comment] 2023-10-11 12:19
@jocelynj @cquest des news sur l'affaire ? :)

**Comment by kNsja5w** [comment] 2024-02-16 21:20
Nice, perfect! Thanks so much!

**Closed** 2024-02-16 23:51 UTC
Labels: support
