### ISSUE TITLE
Whom to ask for the information about the map (uMap) view statistics

### ISSUE THREAD

**Issue by ITsupport-Gong** [umap-project/umap#1731] opened 2024-04-05 07:16 UTC
I just made my first map in uMap (btw excellent tool). Just, i really need the view statistics, nothing particular, just the number of views after, let's say, couple of days.

Perfect would be to have some integrated counter of it.

But, for my particular map that i have just created, to me would be enough good if i could get the number of views after a week or two from some instance. Is there any instance and any way to ask somebody, somehow for this information?

Thank you very much.

**Comment by yohanboniface** [comment] 2024-04-15 07:44
uMap does not have any statistics of maps usage. Some instance may add a tracker, but it is not the case for umap.openstreetmap.fr at least.

Closing as duplicate of #794

**Closed by yohanboniface** 2024-04-15 07:44 UTC
Labels: enhancement
