### ISSUE TITLE
Keep right sidebar open after deleting a layer

### ISSUE THREAD

**Issue by unpack5** [umap-project/umap#691] opened 2019-05-18 18:47 UTC
When you delete a layer from the right sidebar, the sidebar closes. This is annoying. Keep it open.

**Comment by yohanboniface** [comment] 2023-06-23 13:04
cf #190 #330 #1139

**Comment by yohanboniface** [comment] 2023-11-27 22:09
Duplicate of #498

**Closed by yohanboniface** 2023-11-27 22:09 UTC
Labels: enhancement
